INSERT INTO data_provinsi(id, nama_provinsi) VALUES (1, 'ACEH');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (2, 'SUMATERA UTARA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (3, 'SUMATERA BARAT');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (4, 'RIAU');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (5, 'JAMBI');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (6, 'SUMATERA SELATAN');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (7, 'BENGKULU');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (8, 'LAMPUNG');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (9, 'KEPULAUAN BANGKA BELITUNG');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (10, 'KEPULAUAN RIAU');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (11, 'DAERAH KHUSUS IBUKOTA JAKARTA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (12, 'JAWA BARAT');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (13, 'JAWA TENGAH');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (14, 'DAERAH ISTIMEWA YOGYAKARTA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (15, 'JAWA TIMUR');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (16, 'BANTEN');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (17, 'BALI');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (18, 'NUSA TENGGARA BARAT');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (19, 'NUSA TENGGARA TIMUR');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (20, 'KALIMANTAN BARAT');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (21, 'KALIMANTAN TENGAH');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (22, 'KALIMANTAN SELATAN');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (23, 'KALIMANTAN TIMUR');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (24, 'KALIMANTAN UTARA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (25, 'SULAWESI UTARA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (26, 'SULAWESI TENGAH');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (27, 'SULAWESI SELATAN');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (28, 'SULAWESI TENGGARA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (29, 'GORONTALO');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (30, 'SULAWESI BARAT');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (31, 'MALUKU');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (32, 'MALUKU UTARA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (33, 'PAPUA');
INSERT INTO data_provinsi(id, nama_provinsi) VALUES (34, 'PAPUA BARAT');
