INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (1, 'PIDIE JAYA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (2, 'SIMEULUE', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (3, 'BIREUEN', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (4, 'ACEH TIMUR', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (5, 'ACEH UTARA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (6, 'PIDIE', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (7, 'ACEH BARAT DAYA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (8, 'GAYO LUES', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (9, 'ACEH SELATAN', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (10, 'ACEH TAMIANG', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (11, 'ACEH BESAR', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (12, 'ACEH TENGGARA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (13, 'BENER MERIAH', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (14, 'ACEH JAYA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (15, 'LHOKSEUMAWE', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (16, 'ACEH BARAT', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (17, 'NAGAN RAYA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (18, 'LANGSA', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (19, 'BANDA ACEH', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (20, 'ACEH SINGKIL', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (21, 'SABANG', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (22, 'ACEH TENGAH', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (23, 'SUBULUSSALAM', 1);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (24, 'NIAS SELATAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (25, 'MANDAILING NATAL', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (26, 'DAIRI', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (27, 'LABUHAN BATU UTARA', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (28, 'TAPANULI UTARA', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (29, 'SIMALUNGUN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (30, 'LANGKAT', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (31, 'SERDANG BEDAGAI', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (32, 'TAPANULI SELATAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (33, 'ASAHAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (34, 'PADANG LAWAS UTARA', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (35, 'PADANG LAWAS', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (36, 'LABUHAN BATU SELATAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (37, 'PADANG SIDEMPUAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (38, 'TOBA SAMOSIR', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (39, 'TAPANULI TENGAH', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (40, 'HUMBANG HASUNDUTAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (41, 'SIBOLGA', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (42, 'BATU BARA', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (43, 'SAMOSIR', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (44, 'PEMATANG SIANTAR', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (45, 'LABUHAN BATU', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (46, 'DELI SERDANG', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (47, 'GUNUNGSITOLI', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (48, 'NIAS UTARA', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (49, 'NIAS', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (50, 'KARO', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (51, 'NIAS BARAT', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (52, 'MEDAN', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (53, 'PAKPAK BHARAT', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (54, 'TEBING TINGGI', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (55, 'BINJAI', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (56, 'TANJUNG BALAI', 2);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (57, 'DHARMASRAYA', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (58, 'SOLOK SELATAN', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (59, 'SIJUNJUNG (SAWAH LUNTO SIJUNJUNG)', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (60, 'PASAMAN BARAT', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (61, 'SOLOK', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (62, 'PASAMAN', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (63, 'PARIAMAN', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (64, 'TANAH DATAR', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (65, 'PADANG PARIAMAN', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (66, 'PESISIR SELATAN', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (67, 'PADANG', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (68, 'SAWAH LUNTO', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (69, 'LIMA PULUH KOTO / KOTA', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (70, 'AGAM', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (71, 'PAYAKUMBUH', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (72, 'BUKITTINGGI', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (73, 'PADANG PANJANG', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (74, 'KEPULAUAN MENTAWAI', 3);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (75, 'INDRAGIRI HILIR', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (76, 'KUANTAN SINGINGI', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (77, 'PELALAWAN', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (78, 'PEKANBARU', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (79, 'ROKAN HILIR', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (80, 'BENGKALIS', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (81, 'INDRAGIRI HULU', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (82, 'ROKAN HULU', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (83, 'KAMPAR', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (84, 'KEPULAUAN MERANTI', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (85, 'DUMAI', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (86, 'SIAK', 4);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (87, 'TEBO', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (88, 'TANJUNG JABUNG BARAT', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (89, 'MUARO JAMBI', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (90, 'KERINCI', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (91, 'MERANGIN', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (92, 'BUNGO', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (93, 'TANJUNG JABUNG TIMUR', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (94, 'SUNGAIPENUH', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (95, 'BATANG HARI', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (96, 'JAMBI', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (97, 'SAROLANGUN', 5);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (98, 'PALEMBANG', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (99, 'LAHAT', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (100, 'OGAN KOMERING ULU TIMUR', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (101, 'MUSI BANYUASIN', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (102, 'PAGAR ALAM', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (103, 'OGAN KOMERING ULU SELATAN', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (104, 'BANYUASIN', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (105, 'MUSI RAWAS', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (106, 'MUARA ENIM', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (107, 'OGAN KOMERING ULU', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (108, 'OGAN KOMERING ILIR', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (109, 'EMPAT LAWANG', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (110, 'LUBUK LINGGAU', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (111, 'PRABUMULIH', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (112, 'OGAN ILIR', 6);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (113, 'BENGKULU TENGAH', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (114, 'REJANG LEBONG', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (115, 'MUKO MUKO', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (116, 'KAUR', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (117, 'BENGKULU UTARA', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (118, 'LEBONG', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (119, 'KEPAHIANG', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (120, 'BENGKULU SELATAN', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (121, 'SELUMA', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (122, 'BENGKULU', 7);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (123, 'LAMPUNG UTARA', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (124, 'WAY KANAN', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (125, 'LAMPUNG TENGAH', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (126, 'MESUJI', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (127, 'PRINGSEWU', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (128, 'LAMPUNG TIMUR', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (129, 'LAMPUNG SELATAN', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (130, 'TULANG BAWANG', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (131, 'TULANG BAWANG BARAT', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (132, 'TANGGAMUS', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (133, 'LAMPUNG BARAT', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (134, 'PESISIR BARAT', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (135, 'PESAWARAN', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (136, 'BANDAR LAMPUNG', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (137, 'METRO', 8);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (138, 'BELITUNG', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (139, 'BELITUNG TIMUR', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (140, 'BANGKA', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (141, 'BANGKA SELATAN', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (142, 'BANGKA BARAT', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (143, 'PANGKAL PINANG', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (144, 'BANGKA TENGAH', 9);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (145, 'KEPULAUAN ANAMBAS', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (146, 'BINTAN', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (147, 'NATUNA', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (148, 'BATAM', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (149, 'TANJUNG PINANG', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (150, 'KARIMUN', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (151, 'LINGGA', 10);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (152, 'JAKARTA UTARA', 11);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (153, 'JAKARTA BARAT', 11);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (154, 'JAKARTA TIMUR', 11);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (155, 'JAKARTA SELATAN', 11);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (156, 'JAKARTA PUSAT', 11);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (157, 'KEPULAUAN SERIBU', 11);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (158, 'DEPOK', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (159, 'KARAWANG', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (160, 'CIREBON', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (161, 'BANDUNG', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (162, 'SUKABUMI', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (163, 'SUMEDANG', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (164, 'INDRAMAYU', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (165, 'MAJALENGKA', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (166, 'KUNINGAN', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (167, 'TASIKMALAYA', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (168, 'CIAMIS', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (169, 'SUBANG', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (170, 'PURWAKARTA', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (171, 'BOGOR', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (172, 'BEKASI', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (173, 'GARUT', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (174, 'PANGANDARAN', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (175, 'CIANJUR', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (176, 'BANJAR', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (177, 'BANDUNG BARAT', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (178, 'CIMAHI', 12);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (179, 'PURBALINGGA', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (180, 'KEBUMEN', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (181, 'MAGELANG', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (182, 'CILACAP', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (183, 'BATANG', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (184, 'BANJARNEGARA', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (185, 'BLORA', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (186, 'BREBES', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (187, 'BANYUMAS', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (188, 'WONOSOBO', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (189, 'TEGAL', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (190, 'PURWOREJO', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (191, 'PATI', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (192, 'SUKOHARJO', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (193, 'KARANGANYAR', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (194, 'PEKALONGAN', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (195, 'PEMALANG', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (196, 'BOYOLALI', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (197, 'GROBOGAN', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (198, 'SEMARANG', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (199, 'DEMAK', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (200, 'REMBANG', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (201, 'KLATEN', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (202, 'KUDUS', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (203, 'TEMANGGUNG', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (204, 'SRAGEN', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (205, 'JEPARA', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (206, 'WONOGIRI', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (207, 'KENDAL', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (208, 'SURAKARTA (SOLO)', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (209, 'SALATIGA', 13);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (210, 'SLEMAN', 14);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (211, 'BANTUL', 14);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (212, 'YOGYAKARTA', 14);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (213, 'GUNUNG KIDUL', 14);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (214, 'KULON PROGO', 14);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (215, 'GRESIK', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (216, 'KEDIRI', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (217, 'SAMPANG', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (218, 'BANGKALAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (219, 'SUMENEP', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (220, 'SITUBONDO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (221, 'SURABAYA', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (222, 'JEMBER', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (223, 'PAMEKASAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (224, 'JOMBANG', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (225, 'PROBOLINGGO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (226, 'BANYUWANGI', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (227, 'PASURUAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (228, 'BOJONEGORO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (229, 'BONDOWOSO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (230, 'MAGETAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (231, 'LUMAJANG', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (232, 'MALANG', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (233, 'BLITAR', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (234, 'SIDOARJO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (235, 'LAMONGAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (236, 'PACITAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (237, 'TULUNGAGUNG', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (238, 'MOJOKERTO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (239, 'MADIUN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (240, 'PONOROGO', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (241, 'NGAWI', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (242, 'NGANJUK', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (243, 'TUBAN', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (244, 'TRENGGALEK', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (245, 'BATU', 15);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (246, 'TANGERANG', 16);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (247, 'SERANG', 16);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (248, 'PANDEGLANG', 16);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (249, 'LEBAK', 16);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (250, 'TANGERANG SELATAN', 16);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (251, 'CILEGON', 16);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (252, 'KLUNGKUNG', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (253, 'KARANGASEM', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (254, 'BANGLI', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (255, 'TABANAN', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (256, 'GIANYAR', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (257, 'BADUNG', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (258, 'JEMBRANA', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (259, 'BULELENG', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (260, 'DENPASAR', 17);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (261, 'MATARAM', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (262, 'DOMPU', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (263, 'SUMBAWA BARAT', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (264, 'SUMBAWA', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (265, 'LOMBOK TENGAH', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (266, 'LOMBOK TIMUR', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (267, 'LOMBOK UTARA', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (268, 'LOMBOK BARAT', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (269, 'BIMA', 18);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (270, 'TIMOR TENGAH SELATAN', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (271, 'FLORES TIMUR', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (272, 'ALOR', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (273, 'ENDE', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (274, 'NAGEKEO', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (275, 'KUPANG', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (276, 'SIKKA', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (277, 'NGADA', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (278, 'TIMOR TENGAH UTARA', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (279, 'BELU', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (280, 'LEMBATA', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (281, 'SUMBA BARAT DAYA', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (282, 'SUMBA BARAT', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (283, 'SUMBA TENGAH', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (284, 'SUMBA TIMUR', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (285, 'ROTE NDAO', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (286, 'MANGGARAI TIMUR', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (287, 'MANGGARAI', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (288, 'SABU RAIJUA', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (289, 'MANGGARAI BARAT', 19);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (290, 'LANDAK', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (291, 'KETAPANG', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (292, 'SINTANG', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (293, 'KUBU RAYA', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (294, 'PONTIANAK', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (295, 'KAYONG UTARA', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (296, 'BENGKAYANG', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (297, 'KAPUAS HULU', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (298, 'SAMBAS', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (299, 'SINGKAWANG', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (300, 'SANGGAU', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (301, 'MELAWI', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (302, 'SEKADAU', 20);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (303, 'KOTAWARINGIN TIMUR', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (304, 'SUKAMARA', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (305, 'KOTAWARINGIN BARAT', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (306, 'BARITO TIMUR', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (307, 'KAPUAS', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (308, 'PULANG PISAU', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (309, 'LAMANDAU', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (310, 'SERUYAN', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (311, 'KATINGAN', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (312, 'BARITO SELATAN', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (313, 'MURUNG RAYA', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (314, 'BARITO UTARA', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (315, 'GUNUNG MAS', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (316, 'PALANGKA RAYA', 21);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (317, 'TAPIN', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (318, 'BANJAR', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (319, 'HULU SUNGAI TENGAH', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (320, 'TABALONG', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (321, 'HULU SUNGAI UTARA', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (322, 'BALANGAN', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (323, 'TANAH BUMBU', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (324, 'BANJARMASIN', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (325, 'KOTABARU', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (326, 'TANAH LAUT', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (327, 'HULU SUNGAI SELATAN', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (328, 'BARITO KUALA', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (329, 'BANJARBARU', 22);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (330, 'KUTAI BARAT', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (331, 'SAMARINDA', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (332, 'PASER', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (333, 'KUTAI KARTANEGARA', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (334, 'BERAU', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (335, 'PENAJAM PASER UTARA', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (336, 'BONTANG', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (337, 'KUTAI TIMUR', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (338, 'BALIKPAPAN', 23);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (339, 'MALINAU', 24);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (340, 'NUNUKAN', 24);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (341, 'BULUNGAN (BULONGAN)', 24);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (342, 'TANA TIDUNG', 24);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (343, 'TARAKAN', 24);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (344, 'BOLAANG MONGONDOW (BOLMONG)', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (345, 'BOLAANG MONGONDOW SELATAN', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (346, 'MINAHASA SELATAN', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (347, 'BITUNG', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (348, 'MINAHASA', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (349, 'KEPULAUAN SANGIHE', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (350, 'MINAHASA UTARA', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (351, 'KEPULAUAN TALAUD', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (352, 'KEPULAUAN SIAU TAGULANDANG BIARO (SITARO)', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (353, 'MANADO', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (354, 'BOLAANG MONGONDOW UTARA', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (355, 'BOLAANG MONGONDOW TIMUR', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (356, 'MINAHASA TENGGARA', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (357, 'KOTAMOBAGU', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (358, 'TOMOHON', 25);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (359, 'BANGGAI KEPULAUAN', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (360, 'TOLI-TOLI', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (361, 'PARIGI MOUTONG', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (362, 'BUOL', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (363, 'DONGGALA', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (364, 'POSO', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (365, 'MOROWALI', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (366, 'TOJO UNA-UNA', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (367, 'BANGGAI', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (368, 'SIGI', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (369, 'PALU', 26);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (370, 'MAROS', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (371, 'WAJO', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (372, 'BONE', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (373, 'SOPPENG', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (374, 'SIDENRENG RAPPANG / RAPANG', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (375, 'TAKALAR', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (376, 'BARRU', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (377, 'LUWU TIMUR', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (378, 'SINJAI', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (379, 'PANGKAJENE KEPULAUAN', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (380, 'PINRANG', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (381, 'JENEPONTO', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (382, 'PALOPO', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (383, 'TORAJA UTARA', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (384, 'LUWU', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (385, 'BULUKUMBA', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (386, 'MAKASSAR', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (387, 'SELAYAR (KEPULAUAN SELAYAR)', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (388, 'TANA TORAJA', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (389, 'LUWU UTARA', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (390, 'BANTAENG', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (391, 'GOWA', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (392, 'ENREKANG', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (393, 'PAREPARE', 27);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (394, 'KOLAKA', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (395, 'MUNA', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (396, 'KONAWE SELATAN', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (397, 'KENDARI', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (398, 'KONAWE', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (399, 'KONAWE UTARA', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (400, 'KOLAKA UTARA', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (401, 'BUTON', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (402, 'BOMBANA', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (403, 'WAKATOBI', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (404, 'BAU-BAU', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (405, 'BUTON UTARA', 28);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (406, 'GORONTALO UTARA', 29);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (407, 'BONE BOLANGO', 29);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (408, 'GORONTALO', 29);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (409, 'BOALEMO', 29);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (410, 'POHUWATO', 29);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (411, 'MAJENE', 30);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (412, 'MAMUJU', 30);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (413, 'MAMUJU UTARA', 30);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (414, 'POLEWALI MANDAR', 30);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (415, 'MAMASA', 30);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (416, 'MALUKU TENGGARA BARAT', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (417, 'MALUKU TENGGARA', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (418, 'SERAM BAGIAN BARAT', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (419, 'MALUKU TENGAH', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (420, 'SERAM BAGIAN TIMUR', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (421, 'MALUKU BARAT DAYA', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (422, 'AMBON', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (423, 'BURU', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (424, 'BURU SELATAN', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (425, 'KEPULAUAN ARU', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (426, 'TUAL', 31);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (427, 'HALMAHERA BARAT', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (428, 'TIDORE KEPULAUAN', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (429, 'TERNATE', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (430, 'PULAU MOROTAI', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (431, 'KEPULAUAN SULA', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (432, 'HALMAHERA SELATAN', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (433, 'HALMAHERA TENGAH', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (434, 'HALMAHERA TIMUR', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (435, 'HALMAHERA UTARA', 32);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (436, 'YALIMO', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (437, 'DOGIYAI', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (438, 'ASMAT', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (439, 'JAYAPURA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (440, 'PANIAI', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (441, 'MAPPI', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (442, 'TOLIKARA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (443, 'PUNCAK JAYA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (444, 'PEGUNUNGAN BINTANG', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (445, 'JAYAWIJAYA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (446, 'LANNY JAYA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (447, 'NDUGA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (448, 'BIAK NUMFOR', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (449, 'KEPULAUAN YAPEN (YAPEN WAROPEN)', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (450, 'PUNCAK', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (451, 'INTAN JAYA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (452, 'WAROPEN', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (453, 'NABIRE', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (454, 'MIMIKA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (455, 'BOVEN DIGOEL', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (456, 'YAHUKIMO', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (457, 'SARMI', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (458, 'MERAUKE', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (459, 'DEIYAI (DELIYAI)', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (460, 'KEEROM', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (461, 'SUPIORI', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (462, 'MAMBERAMO RAYA', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (463, 'MAMBERAMO TENGAH', 33);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (464, 'RAJA AMPAT', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (465, 'MANOKWARI SELATAN', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (466, 'MANOKWARI', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (467, 'KAIMANA', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (468, 'MAYBRAT', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (469, 'SORONG SELATAN', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (470, 'FAKFAK', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (471, 'PEGUNUNGAN ARFAK', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (472, 'TAMBRAUW', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (473, 'SORONG', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (474, 'TELUK WONDAMA', 34);
INSERT INTO data_kota(id, nama_kota, provinsi_id) VALUES (475, 'TELUK BINTUNI', 34);
